### PR TITLE
gulp-rimraf is deprecated in favour of del

### PR DESCRIPTION
**Pull request by tancnle**
https://github.com/gulpjs/gulp/blob/master/docs/recipes/delete-files-folder.md

NOTE: gulp.src is costly too

### CODE REVIEW

**Comment by markdalgleish** [comment]
Thanks for the pull request :)

Since you opened this pull request, the gulpfile has been updated a couple of times.

Would you be able to do a couple of things, and then I'll merge this in:

1. Rebase off the latest master
2. Update the `clean:pdf` task
3. Wire up the `done` callback for the clean tasks since `del` is an asynchronous operation ([example](https://github.com/gulpjs/gulp/blob/master/docs/recipes/delete-files-folder.md))

**Comment by tancnle** [comment]
Not a problemo :+1:

**Comment by tancnle** [comment]
Oh oh seems like I have stuffed up the PR :sob:

**Comment by tancnle** [comment]
Let me create a new one

**Pull request closed without merging**
