### PR TITLE
adding optional bespoke-pdf plugin

### PR DESCRIPTION
**Pull request by davidmarkclements**
let's do this

### CODE REVIEW

**Comment by markdalgleish** [comment]
So this looks pretty good, but I'm experiencing a few issues:

 - The gulpfile is invalid if I opt out of the PDF option. It seems there's a syntax error for the default task.
 - I'm not sure why, but live reload doesn't appear to work. When I switch back to the latest stable generator, I don't have any trouble.
 - I know this is very picky, but the alignment and whitespace in the resulting gulpfile isn't perfect ;)

Also, the requirement for the `exit` task concerns me a little. Why is this not handled by the gulp task?

**Comment by markdalgleish** [comment]
On further investigation, it seems that the use of `run-sequence` is what caused livereload to break.

**Comment by davidmarkclements** [comment]
1. Good catch, I'll fix it
2. Okay... Tbh gulp-connect has been the source of a lot of niggles (see 4)
3. Absolutely agree white space should be correct (I thought it was.. will look into)
4. The exit task is included because when you try to kill the server (connect.closeServer) it actually freezes the terminal - you literally have to close the terminal tab 

the live reload may be to do with run sequence but I think it's related to a larger asynchronous picture - the connect server doesn't use the done callback anymore (because no opn in task) so it's effectively a parallel task. As far as I could tell gulp-connect doesn't provide a ready callback.  The fact that it worked consistently before is because the opn call took longer to complete than it took the server to start - If we put a setTimeout into the connect task and called done it would prove that but it's a nasty approach.

**Comment by markdalgleish** [comment]
I figured out how to fix the live reload issue:

First, make the `open` task depend on the `connect` task:

```js
gulp.task('open', ['connect'], function (done) {
  opn('http://localhost:8080', done);
})
```

Then, use task dependencies for the `serve` task like so:

```js
gulp.task('serve', ['open', 'watch']);
```

**Comment by markdalgleish** [comment]
Also, I was able to avoid using `run sequence` for the default task like this:

```js
gulp.task('default', ['build', 'pdf', 'exit']);
```

`exit` depends on `pdf`:
```js
gulp.task('exit', ['pdf'], function () {
  process.exit();
});
```

`pdf` depends on `connect`:
```js
gulp.task('pdf', ['build', 'connect'], function () {
  return pdf(pkg.name + '.pdf')
    .pipe(gulp.dest('dist'))
});
```

**Comment by markdalgleish** [comment]
Looks like all the issues are solvable :) I'm looking forward to getting this merged in.

**Comment by davidmarkclements** [comment]
sweet! I'll update the PR

**Comment by davidmarkclements** [comment]
ok that's it 

1. correct whitespace with or without pdfs
2. dependencies linked as suggested
3. livereload confirmed to work with and without pdfs

I think the reason I didn't link them in the first place is so they could be 
independently resuasable, but if run-sequence is causing hassle 
and you're okay with the co-deps then I am too

So one last thing, the pdf partials that get injected into the gulpfile template,
are we happy to leave them inline or should they be broken into a partials
folder and loaded via fs

**Comment by markdalgleish** [comment]
This is looking great :)

Not too worried about the pdf partials right now, as long as it works. I might tweak it later, but that won't affect end users so it's not a big deal right now.

Could you please make just a few minor changes and I'll be happy to merge this in:

1) Remove the unneeded `run-sequence` dependency from `package.json`
2) Ensure there's a line break at the end of `gulpfile.js`
3) Remove the trailing space at the end of `gulp.task('pdf', ['connect'], function () { `
4) Squash all your changes into a single commit

**Comment by davidmarkclements** [comment]
done :)

**Comment by markdalgleish** [comment]
:tada:

**Comment by markdalgleish** [comment]
Just making a few minor changes before I publish a new version.

The biggest change is that resulting pdf won't be generated inside `dist` since that is part of the git history for the `gh-pages` branch. It's a big file that will change on almost every commit, and doesn't really need to be published in most cases.

**Pull request merged**
